### ISSUE TITLE
Topological Sort Bfs Segmentation Fault

### ISSUE THREAD

**Issue by viddrobnic** [KrozekGimVic/Grafi#1]
`topological_sort_bfs_test` crashes with segmentation fault.

**Comment by jureslak** [comment]
Can you be more specific, what do I have to run? 
Running `./bin/tests` (the only possible executable) seems ok, eventhough tests for this function are missing.

**Comment by jureslak** [comment]
I see that they have been commented out. I can confirm the issue.
The bug seems to be on line 8 of `src/topological_sort_bfs.cpp` because the size of the vector is not specified.

**Comment by RokKos** [comment]
Changed line 8 of src/topological_sort_bfs.cpp to `vector<int> ind(N, 0);` so that size of vector is specified.
