### ISSUE TITLE
Make docs command does not work.

### ISSUE THREAD

**Issue by matejm** [KrozekGimVic/Grafi#12]
```
$ cd build/
$ make docs
```

This doesn't change documentation, but this does:

```
$ doxygen docs/Doxyfile
```

**Comment by brecbor** [comment]
nism uspeu se pushat tega sam u Doxyfile mors input nastaut na ../src/

**Comment by jureslak** [comment]
I have fixed the problematic line in `CmakeLists.txt`. What was missing was the `WORKING_DIRECTORY` directive. Now you can generate docs by runnig `make docs` in your build folder or via `./full_test.sh -d` or manually by `doxygen docs/Doxyfile`.

**Comment by jureslak** [comment]
See bbb26628.
