### ISSUE TITLE
Re-explain idea how to check if graph is topological sorted

### ISSUE THREAD

**Issue by RokKos** [KrozekGimVic/Grafi#16]
Mal sm ze pozabu, kako bi se lotu tega, da ce mam vec moznih topoloskih sortirnih rezultatov, da preverem ce je rezultat pravilen. Sklepam da bi mogla bit funkcija v  topological_sort_bfs.cpp al pa mogoce kr v utils.hpp ker jo bo tud @DzinVision rabu. Naj bi bla nekak take oblike: 

```
bool check_topological_sort(const vector<int>& result)
```

**Comment by viddrobnic** [comment]
Funckija rabi verjetno sprejeti tudi graf, da lahko dobi podatke o povezavah.

**Comment by jureslak** [comment]
Hmm, ja, načelno jo bosta potrebovala oba. Taprava stvar bi verjetno bila, da se mergata ona fajla v en fajl `topological_sort.cpp`. Sicer pa ja, napišeš funkcijo 
`is_toppologically_ordered(const vector<int>& vertices, const graf_t& dag) {...}`. Rabi tudi graf, kot je rekel @DzinVision.
Seveda najprej napišeš teste za to funkcijo, potem pa s to funkcijo preveriš neenolične rezultate. 
Funkcjia pa re preprosto po povezavah grafa in preveri, ali jim je zadoščeno --> torej, ko najde povezavo i -> j, potem se mora `i` nahajati v vrstnem redu pred `j`. Za to da ne boš vsakič iskel kje je `i` in kje je `j` pa si v narepj naračunaš njihove pozicije v neko drugo tabelo.
